// app/layout.tsx
import type { Metadata } from "next";
import React from "react";
import styles from "../styles/Home.module.css";
import "./globals.css";
import { Providers } from "./providers";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "../../config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialState = cookieToInitialState(
    config,
    (await headers()).get("cookie")
  );

  return (
    <html lang="en">
      <body className={styles.container}>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  );
}
