// app/layout.tsx
import type { Metadata } from "next";
import React from "react";
import styles from "../styles/Home.module.css";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
